### ISSUE TITLE
How to calculate the abundance of all species within a radius?

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/forum#10]
### Does anyone have code to calculate the abundance of all species withing a radius?

(On behalf of Basset, Yves <BASSETY@si.edu>)

In the CTFS R Package (http://ctfs.si.edu/Public/CTFSRPackage/) the function 
`NeighborDensities()` is close but not exactly what Ives wants. 

Suzanne Lao run `NeighborDensities()` for the species _quaras_:

```
one.sp = subset(bci.full7,  sp == "quaras")
neighbor.counts <- NeighborDensities(bci.full7, one.sp, type='count')
```
The output gives the number of conspecific trees and the number of heterospecific trees within a radius (20 m by default) of each tree of the quaras species. But Yves wants to calculate the abundance of _all_ species. **Does anyone have code to calculate that?**

Please contact Basset, Yves <BASSETY@si.edu> and copy to leporem@si.edu.

**Comment by maurolepore** [comment]
The code that Suzanne run fails on my computer:

```
#> one.sp = subset(bci.full7, sp=="quaras")
#> neighbor.counts <- NeighborDensities(bci.full7, one.sp, type='count')
# Error in .Fortran("inpip", pts[, 1], pts[, 2], as.integer(nptsi), xp,  : 
#   "inpip" not available for .Fortran() for package "splancs"
 ```
That error seems to be not on the R code but on a deeper code written in Fortan languagge inside the package "splancs" (on which NeighborDensities depends). That is unfortunately our of my reach but maybe someone else "speaks" Fortan or they can recommend a function to replace the problematic function "inpip" of the "splancs" pakcage.

**Comment by djj4tree** [comment]
I ran Suzanne's code on my plot data set and had no problems at all. 
The basic approach to counting neighbors tends to be subset the data to a square of the neighborhood size around the focal individual and then subset the circular neighborhood on that subset. Then it's just the number of rows of data for the count of individuals if you don't care about species identity. 
With the function Suzanne supplied you can just add the two vectors and get the total neighbor count.

**Comment by maurolepore** [comment]
This issue was followed up here: https://goo.gl/kjKmGn
Thanks @djj4tree 💯 
Closing this issue now.
