### ISSUE TITLE
Join and propose tutorials

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/forum#2]
Proposed tutorials and people interested are listed here: [here](http://rpubs.com/forestgeo/tutorials).

**Comment by matthewluskin** [comment]
Matthew Luskin

Is this where I sign up for the GitHub tutorial?

**Comment by djj4tree** [comment]
I would like to be a part of an intermediate github session.  Topics should inclede managing workflows and proper push/pull protocols, tidyr and good coding practices

**Comment by jameshogan** [comment]
I am interested in the Git Hub tutorial

**Comment by JessieN** [comment]
I'd like to join an intermediate GitHub session.

**Comment by jonamyers** [comment]
I am interested in an introductory Git Hub tutorial.

**Comment by rutujaCT** [comment]
Interested in both intro & intermediate GitHub tutorial.

**Comment by teixeirak** [comment]
I'm interested in an intermediate level session.

**Comment by RutujaCT** [comment]
I'm interested in a tutorial on 'structured workflow':
https://www.kirchkamp.de/oekonometrie/pdf/wf-screen2.pdf

**Comment by ljvrodriguez** [comment]
I'm interested in GitHub tutorial 2.

**Comment by hqzzlo** [comment]
I'm interested in both tutorial 1&2, thanks.

**Comment by iverenabiem** [comment]
Interested in tutorials

**Comment by ervanSTRI** [comment]
Interested in all tutorials. Thks
